on:
  workflow_dispatch:
jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          depracated= true
          if [[ depracated ]]; then
            echo " ::warning::Deprecated Function Found"
          fi
          
    
