on:
  push:
    branches:
      - "main"
  pull_request:
     branches-ignore:
       - "features/**"
  repository_dispatch:
    types: [build]
jobs: 
    simple-java-app:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6.0.2
        - name: Build the app
          run: mvn clean package
          shell: bash  
                
